### ISSUE TITLE
ban_finetune.py doesn't work

### ISSUE THREAD

**Issue by lansing001** [xiaoyunxxy/ban#2]
Hi! I'm trying to run ban_finetune.py but it's not working.

it can't import the package, and I see the ted folder is empty.

Is there something wrong with what I'm doing?

![image](https://github.com/user-attachments/assets/056baa58-f9d3-4b10-b5cd-ae1ac28f98c9).

**Comment by xiaoyunxxy** [comment]
Hi,
The ted folder contains code for SSDT, which can be found at this link: https://github.com/tedbackdoordefense/ted 

The empty folder might be a soft link. I will revise it.

Best,

**Comment by xiaoyunxxy** [comment]
Hi,

The ted and bpp folders in train_models are updated.

**Comment by lansing001** [comment]
> Hi,  你好，
> 
> The ted and bpp folders in train_models are updated.train_models 中的 ted 和 bpp 文件夹已更新。

Thanks !!!
